# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

pip install selenium webdriver-manager

!apt-get update
!wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
!dpkg -i google-chrome-stable_current_amd64.deb
!apt-get install -f # Install dependencies if any
!pip install --upgrade webdriver-manager

import time
import os
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from webdriver_manager.chrome import ChromeDriverManager

def extrair_eventos_glide(url):
    """
    Acessa a página do Glide usando um navegador invisível e extrai os textos visíveis.
    """
    print("Iniciando o navegador...")

    # Configurar o Chrome para rodar em modo headless (sem abrir a janela gráfica)
    chrome_options = Options()
    chrome_options.add_argument("--headless")
    chrome_options.add_argument("--no-sandbox") # Adicionado para rodar em ambientes como Colab
    chrome_options.add_argument("--disable-dev-shm-usage") # Adicionado para evitar problemas de memória em containers
    chrome_options.add_argument("--log-level=3")

    # Instala e inicializa o ChromeDriver automaticamente
    servico = Service(ChromeDriverManager().install())
    driver = webdriver.Chrome(service=servico, options=chrome_options)

    eventos_encontrados = []

    try:
        print(f"Acessando a página: {url}")
        driver.get(url)

        # O Glide demora alguns segundos para renderizar o banco de dados na tela.
        # Pausamos o script para garantir que os itens da programação apareçam.
        print("Aguardando o carregamento dos eventos dinâmicos...")
        time.sleep(10)

        # Estratégia: O Glide costuma organizar os itens de lista em divs com role="listitem"
        elementos = driver.find_elements(By.CSS_SELECTOR, "div[role='listitem']")

        if not elementos:
            print("Aviso: Nenhuma lista padrão encontrada. Tentando extrair blocos de texto principais...")
            # Fallback: pega o texto do corpo principal do app se a estrutura for diferente
            app_body = driver.find_element(By.ID, "app-root") or driver.find_element(By.TAG_NAME, "body")
            linhas = app_body.text.split('\n')
            # Filtramos linhas que tenham tamanho considerável para ser um evento
            eventos_encontrados = [linha.strip() for linha in linhas if len(linha.strip()) > 5]
        else:
            for elemento in elementos:
                # Pega todo o texto de dentro do card do evento e troca quebras de linha por hífen
                texto = elemento.text.strip()
                if texto:
                    eventos_encontrados.append(texto.replace('\n', ' | '))

    except Exception as e:
        print(f"Erro durante a raspagem de dados: {e}")
    finally:
        driver.quit()

    return eventos_encontrados

def evento_ja_cadastrado_no_portal(evento_texto):
    """
    MOCK (Simulação): Esta função simula a verificação do banco de dados do portal alegrete.org.
    Como não temos acesso ao banco do site, vamos assumir que queremos sugerir todos
    os eventos extraídos, ou você pode inserir palavras-chave aqui para simular a checagem.
    """
    # Exemplo: Se o evento contiver a palavra "Teste", dizemos que já está no site.
    if "Evento Teste" in evento_texto:
        return True

    # Retorna False para indicar que a informação é NOVA e deve ir para o relatório.
    return False

def gerar_relatorio(eventos):
    """
    Compara os eventos encontrados com o portal principal e gera um relatório TXT.
    """
    nome_arquivo = "Relatorio_Atualizacao_Alegrete.txt"
    novos_eventos = []

    # Lógica de comparação (Filtro)
    for evento in eventos:
        if not evento_ja_cadastrado_no_portal(evento):
            novos_eventos.append(evento)

    # Criação do Arquivo TXT
    with open(nome_arquivo, "w", encoding="utf-8") as arquivo:
        arquivo.write("========================================================\n")
        arquivo.write(" RELATÓRIO DE ATUALIZAÇÃO - PROGRAMAÇÃO ALEGRETE.ORG \n")
        arquivo.write("========================================================\n")
        arquivo.write("Fonte verificada: https://eventos-alegrete.glide.page/dl/programacao\n\n")

        if not novos_eventos:
            arquivo.write("Nenhuma nova atualização encontrada. O portal parece estar em dia.\n")
        else:
            arquivo.write(f"Foram identificados {len(novos_eventos)} evento(s) ou informações que PODEM ser cadastrados no portal:\n\n")
            for i, evento in enumerate(novos_eventos, 1):
                arquivo.write(f"[{i}] {evento}\n")
                arquivo.write("-" * 60 + "\n")

    print(f"\n✅ Tarefa concluída! O arquivo '{nome_arquivo}' foi gerado na mesma pasta deste script.")

# --- Execução Principal do Script ---
if __name__ == "__main__":
    URL_ALVO = "https://eventos-alegrete.glide.page/dl/programacao"

    # 1. Extrai os dados do app Glide
    lista_de_eventos = extrair_eventos_glide(URL_ALVO)

    # 2. Gera o relatório com os itens que faltam no portal original
    if lista_de_eventos:
        gerar_relatorio(lista_de_eventos)
    else:
        print("A extração falhou ou a página está vazia. Verifique a conexão ou os seletores do código.")