# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

"""
Estação de Monitoramento de Tensão de Rede (V)
Curso: Elétrica
Faixa válida: 0 a 500 V
Limiar de alerta: desvio acima de 10% do nominal (220 V)
Limiar crítico: desvio acima de 20% do nominal (220 V)
"""

import statistics


# ──────────────────────────────────────────────
# Constantes de configuração
# ──────────────────────────────────────────────
TENSAO_NOMINAL = 220.0   # V
FAIXA_MIN      = 0.0     # V
FAIXA_MAX      = 500.0   # V
LIMIAR_ALERTA  = 0.10    # 10 % de desvio relativo
LIMIAR_CRITICO = 0.20    # 20 % de desvio relativo


# ──────────────────────────────────────────────
# 1. Validação
# ──────────────────────────────────────────────
def validar_medicao(valor) -> bool:
    """Retorna True se o valor é numérico e está dentro da faixa física válida."""
    try:
        v = float(valor)
    except (TypeError, ValueError):
        return False
    return FAIXA_MIN <= v <= FAIXA_MAX


def filtrar_medicoes(medicoes: list) -> tuple[list[float], int]:
    """
    Separa medições válidas das inválidas/fora-de-faixa.

    Retorna:
        validas    – lista de floats aprovados
        descartadas – contagem de valores rejeitados
    """
    validas = []
    descartadas = 0
    for m in medicoes:
        if validar_medicao(m):
            validas.append(float(m))
        else:
            descartadas += 1
    return validas, descartadas


# ──────────────────────────────────────────────
# 2. Estatísticas
# ──────────────────────────────────────────────
def calcular_estatisticas(validas: list[float]) -> dict:
    """
    Calcula média, mínimo, máximo, desvio padrão e total de amostras válidas.
    Retorna dicionário com as chaves: media, minimo, maximo, desvio_padrao, total.
    """
    if not validas:
        return {"media": None, "minimo": None, "maximo": None,
                "desvio_padrao": None, "total": 0}

    return {
        "media":        statistics.mean(validas),
        "minimo":       min(validas),
        "maximo":       max(validas),
        "desvio_padrao": statistics.pstdev(validas),   # desvio padrão populacional
        "total":        len(validas),
    }


# ──────────────────────────────────────────────
# 3. Classificação
# ──────────────────────────────────────────────
def classificar_medicao(valor: float) -> str:
    """
    Classifica uma medição válida em NORMAL, ALERTA ou CRÍTICO
    com base no desvio relativo em relação à tensão nominal.
    """
    desvio_relativo = abs(valor - TENSAO_NOMINAL) / TENSAO_NOMINAL
    if desvio_relativo > LIMIAR_CRITICO:
        return "CRÍTICO"
    if desvio_relativo > LIMIAR_ALERTA:
        return "ALERTA"
    return "NORMAL"


def classificar_todas(validas: list[float]) -> list[tuple[float, str]]:
    """Retorna lista de pares (valor, classificação) para todas as medições válidas."""
    return [(v, classificar_medicao(v)) for v in validas]


# ──────────────────────────────────────────────
# 4. Detecção de eventos críticos
# ──────────────────────────────────────────────
def detectar_eventos_criticos(classificacoes: list[tuple[float, str]]) -> dict:
    """
    Conta o total de medições críticas e encontra a maior sequência
    consecutiva de medições classificadas como CRÍTICO.

    Retorna dicionário com: total_criticos, maior_sequencia_critica.
    """
    total_criticos = sum(1 for _, c in classificacoes if c == "CRÍTICO")

    maior_seq = 0
    seq_atual = 0
    for _, c in classificacoes:
        if c == "CRÍTICO":
            seq_atual += 1
            maior_seq = max(maior_seq, seq_atual)
        else:
            seq_atual = 0

    return {"total_criticos": total_criticos, "maior_sequencia_critica": maior_seq}


# ──────────────────────────────────────────────
# 5. Geração de relatório
# ──────────────────────────────────────────────
def gerar_relatorio(estatisticas: dict, descartadas: int,
                    classificacoes: list[tuple[float, str]],
                    eventos: dict) -> None:
    """Imprime o relatório de diagnóstico formatado no console."""

    sep = "=" * 55

    print(sep)
    print("   RELATÓRIO DE DIAGNÓSTICO – TENSÃO DE REDE (V)")
    print(sep)

    print(f"\n{'RESUMO DE AMOSTRAS':}")
    print(f"  Amostras válidas   : {estatisticas['total']}")
    print(f"  Amostras descartadas: {descartadas}")

    if estatisticas["total"] == 0:
        print("\n  Nenhuma medição válida para analisar.")
        print(sep)
        return

    print(f"\n{'ESTATÍSTICAS':}")
    print(f"  Média              : {estatisticas['media']:.2f} V")
    print(f"  Mínimo             : {estatisticas['minimo']:.2f} V")
    print(f"  Máximo             : {estatisticas['maximo']:.2f} V")
    print(f"  Desvio padrão      : {estatisticas['desvio_padrao']:.2f} V")

    print(f"\n{'CLASSIFICAÇÃO DAS MEDIÇÕES':}")
    print(f"  {'#':<5} {'Valor (V)':<14} {'Estado'}")
    print(f"  {'-'*5} {'-'*14} {'-'*10}")
    for i, (valor, estado) in enumerate(classificacoes, start=1):
        print(f"  {i:<5} {valor:<14.2f} {estado}")

    print(f"\n{'EVENTOS CRÍTICOS':}")
    print(f"  Total de medições críticas        : {eventos['total_criticos']}")
    print(f"  Maior sequência crítica consecutiva: {eventos['maior_sequencia_critica']}")

    print(f"\n  Tensão nominal de referência: {TENSAO_NOMINAL} V")
    print(f"  Limiar de alerta : >{LIMIAR_ALERTA*100:.0f}% de desvio")
    print(f"  Limiar crítico   : >{LIMIAR_CRITICO*100:.0f}% de desvio")
    print(sep)


# ──────────────────────────────────────────────
# 6. Função principal – orquestra o fluxo
# ──────────────────────────────────────────────
def processar_estacao(medicoes: list) -> None:
    """
    Coordena todas as etapas do processamento:
    validação → estatísticas → classificação → eventos → relatório.
    """
    validas, descartadas       = filtrar_medicoes(medicoes)
    estatisticas               = calcular_estatisticas(validas)
    classificacoes             = classificar_todas(validas)
    eventos                    = detectar_eventos_criticos(classificacoes)

    gerar_relatorio(estatisticas, descartadas, classificacoes, eventos)


# ──────────────────────────────────────────────
# Ponto de entrada com dados de teste
# ──────────────────────────────────────────────
if __name__ == "__main__":
    medicoes_teste = [
        220,        # normal
        215,        # normal  (desvio ~2,3 %)
        198,        # alerta  (desvio ~10,0 %)
        185,        # alerta  (desvio ~15,9 %)
        170,        # crítico (desvio ~22,7 %)
        160,        # crítico (desvio ~27,3 %)
        155,        # crítico (desvio ~29,5 %)
        230,        # normal
        260,        # alerta  (desvio ~18,2 %)
        280,        # crítico (desvio ~27,3 %)
        "abc",      # inválido – não numérico
        -5,         # inválido – fora da faixa
        600,        # inválido – fora da faixa
        None,       # inválido – nulo
        220,        # normal
    ]

    processar_estacao(medicoes_teste)