# -*- coding: utf-8 -*-
"""Conheça o Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import math


# =========================
# CONFIGURAÇÕES
# =========================

TENSAO_NOMINAL = 220  # Volts
FAIXA_MIN = 0
FAIXA_MAX = 500


# =========================
# VALIDAÇÃO
# =========================

def validar_medicoes(medicoes):
    validas = []
    descartadas = 0

    for valor in medicoes:
        try:
            valor = float(valor)

            if FAIXA_MIN <= valor <= FAIXA_MAX:
                validas.append(valor)
            else:
                descartadas += 1

        except (ValueError, TypeError):
            descartadas += 1

    return validas, descartadas


# =========================
# CONVERSÃO
# =========================

def converter_unidade(valor):
    """
    Mantida para modularização.
    Neste caso a tensão já está em volts.
    """
    return valor


# =========================
# ESTATÍSTICAS
# =========================

def calcular_media(valores):
    return sum(valores) / len(valores)


def calcular_desvio_padrao(valores):
    media = calcular_media(valores)

    variancia = sum((x - media) ** 2 for x in valores) / len(valores)

    return math.sqrt(variancia)


def calcular_estatisticas(valores):
    return {
        "media": calcular_media(valores),
        "minimo": min(valores),
        "maximo": max(valores),
        "desvio_padrao": calcular_desvio_padrao(valores),
        "quantidade": len(valores)
    }


# =========================
# CLASSIFICAÇÃO
# =========================

def classificar_tensao(valor):
    desvio_percentual = abs(valor - TENSAO_NOMINAL) / TENSAO_NOMINAL * 100

    if desvio_percentual > 20:
        return "CRÍTICO"
    elif desvio_percentual > 10:
        return "ALERTA"
    else:
        return "NORMAL"


def classificar_medicoes(valores):
    classificacoes = []

    for valor in valores:
        classificacoes.append(
            (valor, classificar_tensao(valor))
        )

    return classificacoes


# =========================
# DETECÇÃO DE EVENTOS
# =========================

def eh_critico(valor):
    desvio_percentual = abs(valor - TENSAO_NOMINAL) / TENSAO_NOMINAL * 100
    return desvio_percentual > 20


def detectar_eventos(valores):
    total_criticos = 0
    maior_sequencia = 0
    sequencia_atual = 0

    for valor in valores:

        if eh_critico(valor):
            total_criticos += 1
            sequencia_atual += 1

            if sequencia_atual > maior_sequencia:
                maior_sequencia = sequencia_atual

        else:
            sequencia_atual = 0

    return total_criticos, maior_sequencia


# =========================
# RELATÓRIO
# =========================

def gerar_relatorio(estatisticas,
                    classificacoes,
                    descartadas,
                    total_criticos,
                    maior_sequencia):

    print("\n" + "=" * 50)
    print("RELATÓRIO DE MONITORAMENTO DE TENSÃO")
    print("=" * 50)

    print(f"\nAmostras válidas: {estatisticas['quantidade']}")
    print(f"Amostras descartadas: {descartadas}")

    print("\nESTATÍSTICAS")
    print(f"Média: {estatisticas['media']:.2f} V")
    print(f"Mínimo: {estatisticas['minimo']:.2f} V")
    print(f"Máximo: {estatisticas['maximo']:.2f} V")
    print(f"Desvio padrão: {estatisticas['desvio_padrao']:.2f} V")

    print("\nCLASSIFICAÇÃO DAS MEDIÇÕES")

    for valor, estado in classificacoes:
        print(f"{valor:.2f} V -> {estado}")

    print("\nEVENTOS")
    print(f"Quantidade de medições críticas: {total_criticos}")
    print(f"Maior sequência crítica consecutiva: {maior_sequencia}")

    print("=" * 50)


# =========================
# FUNÇÃO PRINCIPAL
# =========================

def main():

    medicoes_brutas = [
        220,
        215,
        230,
        180,
        270,
        290,
        310,
        225,
        218,
        600,
        -10,
        "erro",
        221
    ]

    validas, descartadas = validar_medicoes(medicoes_brutas)

    convertidas = [converter_unidade(v) for v in validas]

    estatisticas = calcular_estatisticas(convertidas)

    classificacoes = classificar_medicoes(convertidas)

    total_criticos, maior_sequencia = detectar_eventos(convertidas)

    gerar_relatorio(
        estatisticas,
        classificacoes,
        descartadas,
        total_criticos,
        maior_sequencia
    )


if __name__ == "__main__":
    main()